{% set name = "forestplot" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64b0008c65b046076a0ed534d5a3e6ce0480ae4a57c5d8826cf96de9a211cf54

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.6

test:
  imports:
    - forestplot

about:
  home: https://github.com/lsys/forestplot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package to make publication-ready but customizable coefficient plots.
  doc_url: https://forestplot.rtfd.io/
  dev_url: https://github.com/lsys/forestplot

extra:
  recipe-maintainers:
    - lsys
